---
- name: Deploy Tomcat
  hosts: all
  vars:
        tomcat_version: 9.0.20
        java_version: 1.8.0


  tasks:

        - name: Install OpenJDK {{ java_version }}
          yum:
                name: java-{{ java_version }}-openjdk-devel
                state: present

        - name: Create Tomcat group
          group:
                name: tomcat
                state: present

        - name: Create Tomcat user
          user:
                name: tomcat
                password: tomcat
                group: tomcat
                shell: /bin/false
                home: /opt/tomcat

        - name: Download Tomcat
          get_url:
                url: http://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
                dest: /opt/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz

        - name: Extract tar file
          unarchive:
                remote_src: yes
                src: /opt/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz
                dest: /opt/tomcat/
                owner: tomcat
                group: tomcat

        - name: Create shortcut
          file:
                src: /opt/tomcat/apache-tomcat-{{ tomcat_version }}
                dest: /opt/tomcat/latest
                state: link

        - name: Make the scripts inside the bin directory executable
          shell: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'

        - name: Create a systemd unit file
          copy: src=./tomcat.service dest=/etc/systemd/system/tomcat.service

        - name: Start service tomcat
          service:
                name: tomcat
                enabled: yes
                state: started
