---
- name: Check if Tomcat Process Running
  service:
        name: tomcat
        state: started

- name: Check if Nginx Process Running
  service:
        name: nginx
        state: started

- name: Check if Java is Installed
  shell: java -version | grep version | awk '{print $3}'

- name: Check if Tomcat Responds 200
  shell: curl -sL -w "%{http_code}" localhost:8080 | grep 200

- name: Check if it's really Tomcat
  shell: curl -s localhost:8080 | grep 'Apache Tomcat'
