---
- name: Install OpenJDK {{ java_version }}
  yum:
        name: java-{{ java_version }}-openjdk-devel
        state: present

- name: List java packages and register result to print with debug later
  shell: yum list installed java-{{ java_version }}-openjdk-devel
  args:
        warn: false
  register: java_result

- name: Debug java
  debug:
        var: java_result.stdout_lines

- name: Install Epel-release
  yum:
        name: epel-release
        state: present

- name: Install Nginx
  yum:
        name: nginx
        state: present

- name: List nginx packages and register result to print with debug later
  shell: yum list installed nginx
  args:
        warn: false
  register: nginx_result

- name: Debug nginx
  debug:
        var: nginx_result.stdout_lines                

- name: Manage Nginx cofigs
  template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Start service nginx
  service:
        name: nginx
        enabled: yes
        state: started

- name: Create Tomcat group
  group:
        name: "{{ tomcat_group }}"
        state: present

- name: Create Tomcat user
  user:
        name: "{{ tomcat_user }}"
        password: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        home: "{{ tomcat_home }}"

- name: Download Tomcat
  get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_home }}/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Extract tar file
  unarchive:
        remote_src: yes
        src: "{{ tomcat_home }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home }}/"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        
- name: Create shortcut
  file:
        src: "{{ tomcat_home }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_home }}/latest"
        state: link

- name: Make the scripts inside the bin directory executable
  shell: sh -c 'chmod +x {{ tomcat_home }}/latest/bin/*.sh'

- name: Create a systemd unit file
  copy: src=./tomcat.service dest=/etc/systemd/system/tomcat.service

- name: Start service tomcat
  service:
        name: tomcat
        enabled: yes
        state: started
